project:
  type: website
  output-dir: docs

# Meta
description-meta: "Quarto Academic Website Template adapted by Dr. Gang He"
author-meta: "Bodo Przibilla"

website:
  title: "Bodo Przibilla"
  image: ""
  description: "Description"
 
  navbar:
    background: light  # You can change the background color here

    left:   # You can comment out all navigation items here if you just like to keep the index page only
      - text: Home
        href: index.qmd
      - text: About
        menu:
          #- text: News
          #  href: posts.qmd#category=news
          #- text: Events
          #  href: posts.qmd#category=event      
          - text: Contact
            href: contact.qmd             
      - text: Research
        menu:
          - text: List of Publications
            href: publications.qmd
          #- text: Selected Papers
          #  href: posts.qmd#category=paper
          - text: Projects
            href: projects.qmd                                
#      #- text: Teaching # Comment the Teaching part out to remove the Teaching page
#       # href: teaching.qmd
#      #- text: Outreach
#       # menu:        
#       # - text: Presentations
#       #   href: posts.qmd#category=presentation                   
#      #- text: Group   # Comment the Group part out to remove the Group page
#       # href: people.qmd

    right: 
      - text: CV
        href: files/nsf-biosketch.pdf
      - icon: github
        href: https://github.com/drganghe/quarto-academic-website-template
        target: _blank
  
  page-navigation: true
  
  page-footer: 
    left: "[Bodo Przibilla](http://www.github.com) &copy; <script>document.write(new Date().getFullYear())</script>" 
    center: "text"
    right:  
      - icon: github
        href: https://github.com/drganghe/quarto-academic-website-template
        target: _blank
  
  search:
    location: navbar
    type: textbox
  
  reader-mode: true

  draft-mode: unlinked
  
  repo-url: https://github.com/drganghe/quarto-academic-website-template
#  repo-actions: [edit, issue, source]
  
  open-graph: true
  
  twitter-card: true 
#  card-style: summary      
  
  site-url: "https://drganghe.github.io/quarto-academic-website-template"
  
  google-analytics:
    tracking-id: ""  # Please delete or replace with your own tracking ID
    anonymize-ip: true 

bibliography: references.bib  # Add references.bib to the root folder to enable the bibliography function

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/bodoprzibilla\.github\.io\/custom'
    include-in-header: "files/includes/_academic.qmd"

